# Generated by Django 3.1.4 on 2021-07-06 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_lease_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='username',
        ),
        migrations.AddField(
            model_name='lease',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
