# Generated by Django 3.1.4 on 2021-07-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210706_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='user',
            new_name='leasee',
        ),
    ]
